name: 'Get Task Info'
description: 'Greet someone and record the time'
inputs:
  task_url:
    description: 'Asana task url'
    required: true
  asana_token:
    description: 'Asana access token'
    required: true
  distance_to_root:
    description: 'Distance to root task'
    required: true
outputs:
  task_info:
    description: 'The Info of the task'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.task_url }}
    - ${{ inputs.asana_token }}
    - ${{ inputs.distance_to_root }}
